In [3]:
import sys,os
import cv2
import caffe
import numpy as np

In [4]:
net_file = '/home/yaowanchao/code/MobileNet-SSD/MobileNetSSD_deploy_small.prototxt'
caffe_model = '/home/yaowanchao/code/MobileNet-SSD/ZY_MobileNetSSD_deploy_small.caffemodel'
test_dir = '/home/zhongxuexian/20180814.avi'

if not os.path.exists (caffe_model):
    print "caffemodel does not exist"
    exit()

net = caffe.Net(net_file, caffe_model, caffe.TEST)


In [18]:
import copy
CLASSES = ('background', 'car', 'bus', 
           'track', 'person', 'bicycle', 'motor','tricycle','block')
cap = cv2.VideoCapture(test_dir)
video_dir='/home/zhongxuexian/20180814_match.avi'
fps=cap.get(cv2.CAP_PROP_FPS)
size=(int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), 
        int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWriter=cv2.VideoWriter(video_dir, cv2.VideoWriter_fourcc('M','J','P','G'),fps,size)
flag=False
cnt=0
used_tracked_id=0

while(cap.isOpened()):
    print "=========================="
    print cnt
    if flag==True:
        pre_bbox_feature=bbox_feature.copy()
        pre_track_id=track_id.copy()
    ret,frame = cap.read()
    if ret==False:
        break
    img = frame
    mean = (104, 117, 123)
    img1 = img.copy()
    img = (img - mean)/127.5
    img = img.astype(np.float32)
    img = img.transpose((2,0,1))
    
    net.blobs['data'].data[...] = img[:,80:480,:]
    out = net.forward()
    feat_name = 'conv0'
    feat_data = net.blobs[feat_name].data
    detect_out_name = 'detection_out'
    bbox_data = net.blobs[detect_out_name].data
    bbox = np.empty([bbox_data.shape[2],4],dtype=int)
    k=0
    for i in range(0,bbox_data.shape[2]):
        if bbox_data[0,0,i,2]>0.29 and bbox_data[0,0,i,5]-bbox_data[0,0,i,3]>45.0/640.0 and bbox_data[0,0,i,6]-bbox_data[0,0,i,4]>30.0/400.0 and bbox_data[0,0,i,3]>40.0/640.0 and bbox_data[0,0,i,4]>20.0/400.0 and bbox_data[0,0,i,5]<600.0/640.0 and bbox_data[0,0,i,6]<360.0/400.0:
            bbox[k,0]=(bbox_data[0,0,i,3]*img1.shape[1]).astype(np.int)
            bbox[k,1]=(bbox_data[0,0,i,4]*(img1.shape[0]-80)).astype(np.int)
            bbox[k,2]=(bbox_data[0,0,i,5]*img1.shape[1]).astype(np.int)
            bbox[k,3]=(bbox_data[0,0,i,6]*(img1.shape[0]-80)).astype(np.int)
            print bbox[k,:]
            k=k+1
        #print bbox_data[0,0,i,3]
        #print bbox_data[0,0,i,4]
        #print bbox_data[0,0,i,5]
        #print bbox_data[0,0,i,6]
        #print "++++"
        #print bbox[k-1,2]
        #print bbox[k-1,0]
        #print bbox[k-1,3]
        #print bbox[k-1,1]
        #print k
    bbox=bbox[0:k,0:4]
    bbox_feature = np.zeros([feat_data.shape[1],bbox.shape[0],2400])
    for i in range(0,bbox.shape[0]):
        for k in range(0,feat_data.shape[1]):
            fea_tmp=feat_data[0,k,int(bbox[i,1]/2):int(bbox[i,3]/2),int(bbox[i,0]/2):int(bbox[i,2]/2)]
            #new_tmp=np.resize(fea_tmp, (400))
            cv_tmp=cv2.resize(fea_tmp,(40,60))
            #print "after_resize"
            #print new_tmp
            #bbox_feature[k,i,:]=new_tmp
            bbox_feature[k,i,:]=np.resize(cv_tmp,(2400))
    if flag == False:
        track_id=np.arange(0,bbox_feature.shape[1])
        used_tracked_id=bbox_feature.shape[1]
        print track_id
        flag=True
    else:
        dist = np.zeros([bbox_feature.shape[1], pre_bbox_feature.shape[1]])
        for i in range(0,bbox_feature.shape[1]):
            for j in range(0,pre_bbox_feature.shape[1]):
                #bbox_noc=np.resize(bbox_feature[:,i,:],(bbox_feature.shape[0]*bbox_feature.shape[2]))
                #pre_bbox_noc=np.resize(pre_bbox_feature[:,j,:],(pre_bbox_feature.shape[0]*pre_bbox_feature.shape[2]))
                #va=np.mat(bbox_noc)
                #vb=np.mat(pre_bbox_noc)
                #numerator=float(va*vb.T)
                #denum=np.linalg.norm(va)*np.linalg.norm(vb)
                #if denum==0:
                    #dist[i,j]=0
                #else:
                    #cos=numerator/denum
                    #dist[i,j]=0.5+0.5*cos
                #print str(i)+' '+str(j)+' '+str(dist[i,j])
                for k in range(0,bbox_feature.shape[0]):
                    #va=np.mat(bbox_feature[k,i,:])
                    #meana=np.mean(va)
                    #vb=np.mat(pre_bbox_feature[k,j,:])
                    #meanb=np.mean(vb)
                    #d1=np.greater_equal(va,meana)
                    #d2=np.greater_equal(vb,meanb)
                    #numerator=float(va*vb.T)
                    #denum=np.linalg.norm(va)*np.linalg.norm(vb)
                    #if denum ==0:
                        #continue
                    #cos=numerator/denum
                    #dist[i,j]+=(0.5+0.5*cos)
                    #dist[i,j]+=np.linalg.norm(bbox_feature[k,i,:]-pre_bbox_feature[k,j,:],ord=1)
                    dist[i,j]+=np.linalg.norm(bbox_feature[k,i,:]-pre_bbox_feature[k,j,:])
                print str(i)+' '+str(j)+' '+str(dist[i,j])
        idx=np.zeros([bbox_feature.shape[1], pre_bbox_feature.shape[1]])
        for i in range(0,dist.shape[0]):
            idx[i,:]=np.argsort(dist[i,:])
        track_id=np.ones([bbox_feature.shape[1]])
        track_id=-track_id
        matched=np.arange(0,bbox_feature.shape[1])
        match_idx=np.ones([2,pre_bbox_feature.shape[1]])
        match_idx=-match_idx
        while not len(matched)==0:
            next_matched=[]
            for i in matched:
                if idx.shape[1]==0:
                    continue
                if idx[int(i),idx.shape[1]-1]==-1:
                    continue
                for k in range(0,idx.shape[1]):
                    if not idx[int(i),k]==-1:
                        max_idx=idx[int(i),k]
                        idx[int(i),k]=-1
                        break
                if match_idx[0,int(max_idx)]==-1:
                    track_id[int(i)]=pre_track_id[int(max_idx)]
                    match_idx[1,int(max_idx)]=dist[int(i),int(max_idx)]
                    match_idx[0,int(max_idx)]=i
                else:
                    if dist[int(i),int(max_idx)]<dist[int(match_idx[0,int(max_idx)]),int(max_idx)]:
                        matched=np.insert(matched, 0,match_idx[0,int(max_idx)])
                        track_id[int(i)]=pre_track_id[int(max_idx)]
                        match_idx[1,int(max_idx)]=dist[int(i),int(max_idx)]
                        match_idx[0,int(max_idx)]=i
                        track_id[int(match_idx[0,int(max_idx)])]=-1
                    else:
                        next_matched=np.append(next_matched,i)
            matched=copy.deepcopy(next_matched)
        for i in range(0,track_id.shape[0]):
            if track_id[i]==-1:
                track_id[i]=used_tracked_id
                used_tracked_id=used_tracked_id+1;
        print track_id
        font =cv2.FONT_HERSHEY_SIMPLEX
        for i in range(0, track_id.shape[0]):
            img1=cv2.rectangle(img1, (bbox[i,0],bbox[i,1]+80),(bbox[i,2],bbox[i,3]+80),(0,255,0),1)
            cv2.putText(img1,'id'+str(track_id[i]),(bbox[i,0],bbox[i,1]+80),font,1,(0,0,255))
            #frame=cv2.rectangle(frame,(int(bbox[i,0]/640.0*frame.shape[0]),int(bbox[i,1]/400.0*frame.shape[1])),(int(bbox[i,2]/640.0*frame.shape[0]),int(bbox[i,3]/400.0*frame.shape[1])),(0,255,0),1)
            #cv2.putText(frame,'id'+str(track_id[i]),(int(bbox[i,0]/640.0*frame.shape[0]),int(bbox[i,1]/400.0*frame.shape[1])),font,1,(0,0,255))
        #cv2.imwrite(str(cnt)+".jpg",img1)
    videoWriter.write(img1)
    cnt=cnt+1
videoWriter.release()
print 'finish'
                

0
[]
1
[]
2
[]
3
[]
4
[]
5
[]
6
[]
7
[]
8
[]
9
[235 141 455 245]
[0.]
10
[237 138 452 245]
0 0 558.237038656429
[0.]
11
[240 129 469 258]
0 0 866.7879073560923
[0.]
12
[]
13
[]
14
[229 140 464 242]
[1.]
15
[235 131 458 243]
0 0 767.4615381662069
[1.]
16
[229 138 466 243]
0 0 787.3326271182334
[1.]
17
[230 139 462 242]
0 0 482.2766518375002
[1.]
18
[251 128 444 242]
[ 43 133 280 247]
0 0 991.7705143083857
1 0 1130.151176577926
[1. 2.]
19
[233 140 463 241]
0 0 1024.8166490915341
0 1 1145.9925592301392
[1.]
20
[217 138 452 241]
0 0 602.6162042396528
[1.]
21
[164 140 404 249]
0 0 720.6620183613301
[1.]
22
[157 136 392 250]
[ 44 158 277 249]
0 0 796.8945282805671
1 0 875.2743061158151
[1. 3.]
23
[]
24
[]
25
[]
26
[]
27
[]
28
[]
29
[366 140 501 196]
[4.]
30
[]
31
[]
32
[]
33
[]
34
[ 51 161 194 250]
[5.]
35
[]
36
[]
37
[ 75 155 250 298]
[ 43 163 110 237]
[6. 7.]
38
[148 142 332 301]
[ 89 163 184 245]
0 0 1088.4403417558583
0 1 1306.5319930712656
1 0 1264.2569914662424
1 1 951.0596455491018
[6

[]
73
[]
74
[]
75
[106 177 177 243]
[170 166 252 225]
[25. 26.]
76
[161 169 262 249]
0 0 968.5455274086022
0 1 1206.8545718597986
[25.]
77
[ 54 163 186 246]
[148 170 245 225]
[245 171 309 233]
0 0 1167.1384756270486
1 0 1021.9878158571897
2 0 1066.6261717198392
[25. 27. 28.]
78
[ 94 165 199 241]
[144 167 247 221]
[482 167 566 231]
0 0 889.9415697073265
0 1 908.9986344255191
0 2 1108.0487795803842
1 0 1018.1942670564067
1 1 1107.507726899351
1 2 1296.114536530363
2 0 982.9593417840379
2 1 936.1488140202173
2 2 1040.298101421031
[25. 28. 27.]
79
[435 139 539 220]
[ 91 162 194 223]
[283 171 330 238]
0 0 919.0668753391882
0 1 1088.4861854837427
0 2 906.5785497140706
1 0 1029.040018889289
1 1 1060.4865537502387
1 2 1025.3026646388535
2 0 1022.0131797140244
2 1 1314.2955710791318
2 2 1109.21458665285
[27. 28. 25.]
80
[ 76 160 201 234]
[451 150 554 231]
0 0 1066.870376374529
0 1 1061.1220094374307
0 2 1301.1962299538682
1 0 988.365469320303
1 1 1064.588119412116
1 2 1283.4374538638697
[28. 27

[272 159 377 235]
[118 169 195 218]
[460 165 524 212]
0 0 556.7876082918115
0 1 765.6600128936917
0 2 828.7271444672116
1 0 783.9827371814469
1 1 832.2868859247224
1 2 784.8922376081873
2 0 796.824322092016
2 1 736.2292518654598
2 2 919.9961306602531
[46. 49. 48.]
166
[275 162 372 222]
[ 42 166 119 215]
[460 159 532 201]
[428 154 506 195]
0 0 774.8703453916719
0 1 877.1728298377942
0 2 899.6475160509808
1 0 656.822438578127
1 1 668.5953558685374
1 2 706.6008610668113
2 0 903.4080466844877
2 1 967.0396789314241
2 2 770.2089036472552
3 0 890.763933834023
3 1 941.9670239892985
3 2 925.7087394953751
[46. 50. 48. 49.]
167
[273 160 366 218]
[475 156 530 199]
0 0 637.8992219011104
0 1 710.9299460457428
0 2 914.7620372286422
0 3 938.2669449679283
1 0 1003.4816683197351
1 1 848.653956907078
1 2 797.2879341037841
1 3 1040.3170804807462
[46. 48.]
168
[262 157 353 218]
0 0 737.5267595224649
0 1 919.6191196051576
[46.]
169
[441 128 594 249]
[250 157 336 219]
[329 155 387 186]
0 0 749.5363208056705


[221 164 320 233]
0 0 460.9972899862697
0 1 480.88035054983203
[67.]
220
[204 157 324 232]
[ 44 167 114 216]
0 0 433.79040339077574
1 0 417.94239517605774
[67. 71.]
221
[228 157 329 227]
[195 159 292 219]
0 0 496.28054935556537
0 1 445.63669270320815
1 0 527.0408133563465
1 1 494.2995977739757
[71. 67.]
222
[265 150 343 216]
[181 154 251 203]
0 0 496.48904446078683
0 1 525.8968962907156
1 0 657.6959083210579
1 1 605.6850998675229
[71. 67.]
223
[288 168 370 229]
[187 168 275 218]
0 0 493.0555718745264
0 1 670.7455883130548
1 0 728.7805169842597
1 1 733.246618396554
[71. 67.]
224
[304 171 388 227]
[171 169 258 226]
[ 60 174 148 218]
[276 175 354 217]
[241 177 287 214]
0 0 483.41133120086005
0 1 727.9497466344817
1 0 518.6814922315147
1 1 689.9568872626558
2 0 528.6875011341434
2 1 733.5217821845763
3 0 698.8169102558777
3 1 795.2585131804337
4 0 776.1470276439042
4 1 834.5029120000713
[71. 67. 72. 73. 74.]
225
[320 148 410 216]
[141 147 250 213]
[179 154 276 208]
[392 155 473 199]
0 0 44

[273 120 392 235]
0 0 262.22820959446165
[92.]
278
[ 63 122 263 291]
[280 114 404 239]
0 0 575.176920250848
1 0 246.4630337213765
[92. 94.]
279
[ 62 132 264 297]
[274 117 402 244]
0 0 524.5480490003071
0 1 612.5344362101648
1 0 556.6265354562794
1 1 325.57429999266475
[92. 94.]
280
[272 118 410 255]
[ 69 134 269 294]
[435 144 597 257]
0 0 598.4047819510055
0 1 308.0064380172858
1 0 462.3224786076488
1 1 580.4869536722526
2 0 650.9874141885728
2 1 469.371517618853
[94. 92. 95.]
281
[295 122 425 256]
[441 144 576 254]
[ 81 141 273 296]
0 0 328.8934353676688
0 1 586.34502104706
0 2 491.11624569335595
1 0 608.6162163050036
1 1 741.5960642997602
1 2 595.6414068343248
2 0 485.6357872627833
2 1 551.6507258997237
2 2 549.0558282018222
[94. 95. 96.]
282
[297 128 436 255]
[ 63 118 301 305]
0 0 342.7789219159464
0 1 600.5389438692865
0 2 504.348310173976
1 0 536.0703743630014
1 1 693.9334937352563
1 2 602.4868275844606
[94. 96.]
283
[285 121 425 250]
[ 50 129 276 285]
[439 142 599 253]
0 0 296.18

[262 150 363 225]
[ 89 167 141 198]
0 0 901.0730075897674
0 1 1196.2180962136713
1 0 1115.4509239304346
1 1 1193.2720583887155
[106. 115.]
320
[280 162 368 236]
[ 46 174 123 213]
0 0 872.4818188259862
0 1 1076.4393778354242
1 0 1153.3986346349952
1 1 1027.7924955345293
[106. 115.]
321
[429 164 563 269]
[288 148 380 215]
0 0 1162.1848314732026
0 1 1134.9113977866537
1 0 1070.1559807927028
1 1 1294.9584714058328
[115. 106.]
322
[334 167 592 311]
[281 163 344 227]
0 0 947.1602325455535
0 1 1374.7985992489112
1 0 1211.7829798463517
1 1 1227.3645074707676
[115. 106.]
323
[293 135 517 276]
0 0 1013.0487625190693
0 1 1216.0711526261334
[115.]
324
[193 138 394 280]
[378 146 485 238]
0 0 1111.017586411228
1 0 1080.9163238744572
[115. 116.]
325
[365 155 489 248]
[149 152 336 292]
0 0 1074.734459134427
0 1 859.9023916074124
1 0 885.7415716837053
1 1 1048.7247321581833
[116. 115.]
326
[396 143 512 233]
[101 136 302 276]
[284  85 391 204]
0 0 901.6130397924278
0 1 984.1630788367345
1 0 1020.3518618

[151 148 301 244]
[398  67 559 230]
0 0 832.1688780497609
1 0 1376.7525270125577
[130. 131.]
411
[119 167 255 250]
[ 43 168 110 223]
[473 149 584 249]
0 0 1069.3244719901418
0 1 1470.2688033999793
1 0 980.9223246791147
1 1 1394.5002763978691
2 0 1248.1468639449026
2 1 1113.3401881264226
[130. 132. 131.]
412
[ 89 153 206 233]
0 0 903.7045840812033
0 1 919.4391282536807
0 2 1161.620699232253
[130.]
413
[115 147 234 209]
[ 47 142 165 215]
0 0 1186.69579346604
1 0 945.5612228664534
[130. 133.]
414
[ 93 140 224 214]
0 0 955.5147663519627
0 1 1077.7473649212216
[130.]
415
[]
416
[]
417
[]
418
[]
419
[]
420
[]
421
[163 134 272 244]
[ 91 166 144 199]
[134. 135.]
422
[389 129 478 225]
[383 135 482 229]
0 0 1158.1656499756953
0 1 1548.4350995336094
1 0 1123.3378881377669
1 1 1518.3133339204226
[134. 136.]
423
[399 129 488 217]
[397 129 491 217]
0 0 1320.2061318034293
0 1 1242.4425439770387
1 0 1322.0589222256954
1 1 1246.1249868912791
[136. 134.]
424
[399 143 483 229]
[397 143 482 228]
0 0 562.7

[171 193 260 250]
[ 83 195 160 245]
[299 172 377 231]
0 0 360.97130685312356
1 0 467.50505165253634
2 0 946.4019237375238
[162. 163. 164.]
499
[111 187 186 239]
[222 198 301 243]
0 0 1393.7694790438918
0 1 1352.6404545157548
0 2 1381.842299370312
1 0 1205.8389374702301
1 1 1181.7795945023015
1 2 1151.8512597781378
[163. 164.]
500
[135 196 206 243]
[253 201 309 238]
0 0 1266.0314749402
0 1 1234.0375805997019
1 0 1251.1241230379449
1 1 1031.0899145246633
[164. 165.]
501
[276 196 324 231]
0 0 1535.0310047470202
0 1 1285.6612460547092
[165.]
502
[]
503
[]
504
[105 155 235 267]
[166.]
505
[143 159 250 260]
0 0 320.3271775934229
[166.]
506
[163 166 259 256]
0 0 305.412036241383
[166.]
507
[185 164 277 252]
0 0 320.9103425807932
[166.]
508
[196 174 280 248]
0 0 332.4143518142987
[166.]
509
[198 172 282 243]
0 0 331.8986063569359
[166.]
510
[204 167 285 232]
0 0 291.56385900086536
[166.]
511
[183 215 228 245]
[207 198 291 251]
0 0 352.08150837989746
1 0 324.9893117146573
[166. 167.]
512
[]
513

[173 180 273 266]
[332 188 419 252]
0 0 1077.2600438511504
0 1 1078.4325152887673
0 2 996.1967621219928
1 0 1319.0111246233873
1 1 1121.3918614462066
1 2 1161.8313604755738
[189. 188.]
647
[362 188 447 254]
[237 187 323 251]
0 0 1131.8051962481543
0 1 740.9112990903571
1 0 922.673317402015
1 1 1071.331217206262
[188. 189.]
648
[408 189 505 259]
[303 186 372 244]
0 0 815.364500919511
0 1 1125.6772000707804
1 0 1091.4494536900904
1 1 729.5219470652936
[188. 189.]
649
[444 188 549 260]
[350 187 411 236]
0 0 838.1900612399098
0 1 1259.7867112587112
1 0 970.400954055613
1 1 972.1105135017904
[188. 189.]
650
[384 186 441 237]
0 0 949.6568576451033
0 1 729.1861358186053
[189.]
651
[407 183 466 238]
0 0 832.824689604565
[189.]
652
[372 184 439 242]
0 0 924.9480747138648
[189.]
653
[332 177 409 249]
0 0 928.4838326848605
[189.]
654
[324 178 421 255]
[478 175 577 231]
0 0 907.2036108994324
1 0 1208.9974681960712
[189. 190.]
655
[295 180 406 270]
0 0 687.4462178595379
0 1 953.5316510699665
[189.]

[298 194 388 253]
0 0 550.1116835944337
0 1 526.4059270922178
[195.]
734
[225 195 307 248]
0 0 560.6007613783745
[195.]
735
[178 199 243 235]
0 0 610.2760574538606
[195.]
736
[]
737
[252 197 434 294]
[389 208 478 266]
[196. 197.]
738
[148 195 244 261]
0 0 416.6697828586335
0 1 547.6280117858297
[196.]
739
[383 180 510 268]
0 0 441.3114028663162
[196.]
740
[140 195 185 232]
[355 196 425 250]
0 0 496.126989085395
1 0 476.26287973339447
[196. 198.]
741
[259 127 418 284]
[207  34 436 267]
0 0 581.7076204175073
0 1 553.7504096102804
1 0 1007.3733161797535
1 1 951.2993639312145
[198. 196.]
742
[196 177 288 255]
0 0 564.2453397305245
0 1 997.6488062339474
[198.]
743
[]
744
[]
745
[388 161 485 252]
[199.]
746
[366 174 425 239]
0 0 319.447894171898
[199.]
747
[]
748
[]
749
[]
750
[]
751
[228 191 321 246]
[200.]
752
[416 187 478 232]
0 0 1004.5264028424548
[200.]
753
[]
754
[155 201 239 243]
[135 213 198 246]
[188 199 270 240]
[231 197 305 241]
[201. 202. 203. 204.]
755
[202 205 286 252]
[ 66 17

[290 159 500 266]
0 0 698.6228201522143
0 1 669.2435997770953
0 2 679.6846374536779
0 3 694.8701785953639
[230.]
828
[]
829
[]
830
[]
831
[]
832
[347 115 447 229]
[322 120 485 270]
[233. 234.]
833
[]
834
[]
835
[]
836
[]
837
[]
838
[]
839
[]
840
[]
841
[]
842
[]
843
[]
844
[]
845
[]
846
[]
847
[]
848
[]
849
[]
850
[]
851
[]
852
[]
853
[]
854
[]
855
[]
856
[]
857
[]
858
[]
859
[]
860
[]
861
[158 164 315 290]
[235.]
862
[256 175 384 278]
0 0 1104.034035840674
[235.]
863
[321 176 409 254]
0 0 1003.0175500756249
[235.]
864
[330 185 408 253]
0 0 1088.5622733469595
[235.]
865
[341 186 412 251]
0 0 877.004832705781
[235.]
866
[347 180 415 240]
0 0 973.0970133839896
[235.]
867
[342 180 418 241]
0 0 1275.5126486586869
[235.]
868
[331 178 417 245]
0 0 919.5804897158997
[235.]
869
[330 186 425 260]
0 0 903.8532219738142
[235.]
870
[331 177 446 259]
0 0 957.8782648066867
[235.]
871
[336 161 486 283]
0 0 996.4567080398886
[235.]
872
[338 156 524 291]
0 0 1159.1148129436897
[235.]
873
[319 146 527 3

[]
954
[]
955
[]
956
[]
957
[145 138 455 345]
[251.]
958
[150 140 454 344]
0 0 651.1037891254515
[251.]
959
[]
960
[]
961
[]
962
[]
963
[]
964
[153 141 444 342]
[252.]
965
[151 145 444 344]
0 0 1448.7958805392552
[252.]
966
[145 151 450 345]
0 0 884.1193022222626
[252.]
967
[146 146 453 344]
0 0 748.7847791157708
[252.]
968
[138 144 456 345]
0 0 710.3013546616716
[252.]
969
[148 144 449 346]
0 0 778.9633219623508
[252.]
970
[147 145 449 349]
0 0 635.6582590402891
[252.]
971
[153 140 450 338]
0 0 1063.630125726894
[252.]
972
[148 141 452 344]
0 0 915.8299788681246
[252.]
973
[150 144 455 342]
0 0 776.9846362662463
[252.]
974
[140 146 450 344]
0 0 946.6294674007714
[252.]
975
[]
976
[141 148 458 351]
[253.]
977
[]
978
[150 141 454 348]
[254.]
979
[]
980
[]
981
[]
982
[]
983
[148 144 457 351]
[255.]
984
[]
985
[]
986
[]
987
[]
988
[]
989
[147 150 456 346]
[256.]
990
[152 148 456 349]
0 0 629.2724622748132
[256.]
991
[150 149 461 349]
0 0 394.6571306838665
[256.]
992
[]
993
[]
994
[140 149

[346 195 400 228]
0 0 1656.8153733509384
0 1 1604.8876623493752
[272.]
1056
[355 194 401 228]
0 0 1205.6696392361507
[272.]
1057
[]
1058
[336 179 501 298]
[273.]
1059
[285 193 402 283]
[283 151 422 279]
0 0 1064.314835256313
1 0 1294.4917066804983
[273. 274.]
1060
[301 196 402 267]
0 0 1144.7853258687237
0 1 1284.6538589662355
[273.]
1061
[292 196 392 259]
0 0 1117.5025185251243
[273.]
1062
[257 201 331 255]
0 0 1174.325405979827
[273.]
1063
[]
1064
[344 164 515 294]
[275.]
1065
[319 201 451 301]
[484 211 594 276]
0 0 1079.6786483672495
1 0 1777.763576836893
[275. 276.]
1066
[479 202 592 267]
[317 205 414 285]
0 0 1825.0919084935213
0 1 1140.0670766859296
1 0 1527.5770213763178
1 1 2115.5310076461683
[276. 275.]
1067
[476 184 581 251]
[314 187 405 251]
[255 192 303 227]
0 0 828.986567214171
0 1 1788.3509611235077
1 0 1730.3708929947802
1 1 1059.1622309194638
2 0 1817.7372461883358
2 1 1718.9153392672476
[276. 275. 277.]
1068
[479 202 586 264]
[302 201 386 257]
0 0 937.9539701160459
0 1

[342 200 434 265]
[219 195 299 262]
0 0 1248.4191469082702
0 1 1362.9935666296547
1 0 1485.5266927368477
1 1 1190.0048000596953
[299. 300.]
1130
[351 171 511 288]
[254 177 319 231]
0 0 1448.895633143566
0 1 1381.0202829109176
1 0 1579.9487080242102
1 1 1448.4546520298827
[300. 299.]
1131
[302 196 409 263]
0 0 1154.2368134050885
0 1 1437.6261392629128
[300.]
1132
[ 68 193 190 267]
[293 195 379 252]
0 0 1678.0854332580125
1 0 1001.1793521352567
[300. 301.]
1133
[122 202 223 261]
[303 205 376 251]
0 0 1013.7548128015827
0 1 1427.5103185220382
1 0 1608.876121909606
1 1 966.5493642493445
[300. 301.]
1134
[173 195 245 246]
0 0 720.4580508599022
0 1 1175.1906730066378
[300.]
1135
[319 202 368 235]
0 0 1401.1229965490418
[300.]
1136
[235 204 283 242]
0 0 1499.6232034023512
[300.]
1137
[]
1138
[ 88 191 202 264]
[302.]
1139
[155 206 240 259]
0 0 1015.9194330276099
[302.]
1140
[196 202 263 248]
0 0 1021.7694293944855
[302.]
1141
[222 200 276 234]
0 0 896.9818451057592
[302.]
1142
[]
1143
[]
1144


[ 43 178 168 271]
[245 174 388 274]
[ 58 128 269 262]
[254 121 392 267]
[103 110 274 251]
0 0 801.8221027560642
0 1 1176.1179128834692
0 2 1107.1205384037535
0 3 1353.0689796385652
0 4 1242.6238114807288
1 0 1086.4445455904138
1 1 870.9339069294165
1 2 1164.69495877416
1 3 1345.286311342537
1 4 1293.8591128756746
2 0 1180.9167575051974
2 1 1266.3902184340016
2 2 873.2650579741368
2 3 1258.6974990135182
2 4 973.3230554647749
3 0 1303.819390010741
3 1 1286.293120990042
3 2 1164.47265297131
3 3 819.1983858451706
3 4 1344.4260002534927
4 0 1246.968847860477
4 1 1347.510450763119
4 2 1096.522556389166
4 3 1377.9367299061878
4 4 763.6068249516136
[315. 312. 316. 317. 318.]
1222
[240 177 386 286]
[ 63 116 254 258]
0 0 1177.4294762118886
0 1 746.1290313254116
0 2 1275.9712780823395
0 3 1342.9875267630628
0 4 1369.800215039582
1 0 1259.323143589235
1 1 1295.3595586757963
1 2 908.2321403456461
1 3 1321.9098131516157
1 4 799.4849073250032
[312. 318.]
1223
[207 161 384 301]
[ 60 101 240 268]
0 0 9

[135 176 229 256]
0 0 1432.939878656066
0 1 1230.9656105816707
[340.]
1315
[ 51 157 187 279]
[194 197 288 253]
0 0 984.308280951705
1 0 1464.2042010593505
[340. 341.]
1316
[ 91 181 235 283]
0 0 1170.091185917436
0 1 1218.7515784379675
[340.]
1317
[]
1318
[142 190 253 275]
[342.]
1319
[ 99 188 223 278]
0 0 637.0592610296466
[342.]
1320
[]
1321
[224 203 299 245]
[343.]
1322
[103 191 218 261]
[211 188 275 238]
0 0 1380.110114690195
1 0 1530.9085772586864
[343. 344.]
1323
[108 206 222 279]
0 0 1170.1471891358954
0 1 1155.5110822771408
[344.]
1324
[487 183 575 233]
[187 200 243 233]
[ 61 210 111 242]
0 0 1243.5829238531703
1 0 1697.668835541124
2 0 1152.7605522840631
[344. 345. 346.]
1325
[]
1326
[]
1327
[ 83 195 185 248]
[347.]
1328
[]
1329
[]
1330
[ 51 191 179 285]
[348.]
1331
[ 78 189 143 243]
[384 184 480 224]
0 0 925.5850326821168
1 0 834.4819666163404
[348. 349.]
1332
[]
1333
[115 195 210 252]
[350.]
1334
[176 196 247 242]
0 0 1684.5421330725437
[350.]
1335
[138 194 227 262]
0 0 1193.

[]
1421
[]
1422
[164 217 225 250]
[387.]
1423
[ 55 214 145 261]
0 0 945.5509491761494
[387.]
1424
[]
1425
[ 85 234 148 268]
[388.]
1426
[335 201 394 238]
0 0 971.1182461998038
[388.]
1427
[344 187 404 234]
0 0 1069.1800646234221
[388.]
1428
[342 185 407 235]
0 0 1125.2045402748251
[388.]
1429
[322 182 405 252]
0 0 1001.7409933687671
[388.]
1430
[322 174 418 252]
0 0 847.785489423103
[388.]
1431
[326 177 440 265]
0 0 986.23247187246
[388.]
1432
[315 174 460 279]
0 0 929.8068904375006
[388.]
1433
[295 177 468 308]
0 0 1045.0572904335684
[388.]
1434
[280 168 499 321]
0 0 945.8879344623168
[388.]
1435
[253 169 489 334]
0 0 915.677097440583
[388.]
1436
[275 171 517 325]
0 0 1100.8771974454453
[388.]
1437
[256 184 451 335]
0 0 1141.711411991826
[388.]
1438
[240 168 469 335]
0 0 953.1692728796592
[388.]
1439
[277 172 514 332]
0 0 1115.8316858508417
[388.]
1440
[242 166 469 335]
0 0 1127.1042707924948
[388.]
1441
[242 166 469 337]
0 0 392.0710173523471
[388.]
1442
[241 168 469 337]
0 0 471.938

[132 196 229 254]
[319 192 404 255]
[394 201 445 236]
0 0 1352.5005395703367
1 0 786.1984193778123
2 0 1082.448798240047
[394. 398. 399.]
1515
[ 50 185 135 252]
[376 173 529 290]
0 0 1271.3734824558844
0 1 1265.6853683380016
0 2 1359.955056421547
1 0 1362.949873962608
1 1 896.2000512519958
1 2 1007.5233314044455
[398. 400.]
1516
[383 190 480 262]
[136 198 225 260]
0 0 1310.0554071520992
0 1 852.0883626415307
1 0 1213.777916715194
1 1 1139.0710224657105
[400. 398.]
1517
[]
1518
[353 185 480 272]
[498 193 550 226]
[401. 402.]
1519
[319 196 422 261]
[154 203 209 240]
0 0 910.4299088452349
0 1 1169.3814391826293
1 0 1187.1850412088547
1 1 1177.4611088616466
[401. 402.]
1520
[338 201 416 252]
0 0 964.0413120066299
0 1 1112.9326972182607
[401.]
1521
[347 204 417 247]
0 0 826.1703153769388
[401.]
1522
[107 188 242 259]
[362 197 429 243]
0 0 911.6844896063619
1 0 757.2969811306335
[401. 403.]
1523
[113 162 218 266]
[362 201 421 235]
0 0 1028.6425164354032
0 1 995.404002821459
1 0 1022.26839913

[258 209 387 298]
0 0 753.3335443693901
[415.]
1574
[268 213 389 294]
0 0 708.4307878187248
[415.]
1575
[262 191 389 273]
0 0 758.7768003127792
[415.]
1576
[100 196 195 265]
[261 189 382 276]
0 0 986.5769849502798
1 0 822.1426589982657
[415. 423.]
1577
[274 188 392 277]
[166 200 245 259]
0 0 884.4259797105409
0 1 673.920973000962
1 0 859.9272253973206
1 1 1093.4788529817727
[423. 415.]
1578
[284 205 413 298]
0 0 917.2584500021342
0 1 1026.759060613188
[423.]
1579
[281 208 399 291]
0 0 858.5198275973692
[423.]
1580
[288 187 406 271]
[ 89 212 170 261]
0 0 806.8127578788332
1 0 1261.9536639005564
[423. 424.]
1581
[293 220 402 298]
0 0 688.9709050260989
0 1 1254.0121054076676
[423.]
1582
[291 225 401 301]
[ 76 217 137 269]
[199 223 245 255]
0 0 1014.031718451557
1 0 1247.270007707961
2 0 1458.3961555910714
[423. 425. 426.]
1583
[284 180 395 258]
[ 79 182 166 237]
0 0 905.6513123958866
0 1 1213.2874410500624
0 2 1431.6958049836524
1 0 1195.1759935935936
1 1 1151.7719332131962
1 2 1272.26925

[376 163 567 261]
0 0 1070.589632551689
[446.]
1644
[316 179 583 308]
[216 204 276 236]
0 0 1161.8989711127047
1 0 1160.4393296710507
[446. 448.]
1645
[381 149 573 251]
0 0 761.302575661766
0 1 1073.782777785462
[446.]
1646
[319 168 593 306]
[208 182 480 304]
0 0 1000.3028209334901
1 0 1189.832159664435
[446. 449.]
1647
[298 151 517 249]
0 0 1067.3945081337
0 1 1258.9323839332542
[446.]
1648
[]
1649
[ 84 191 338 307]
[432 171 547 249]
[450. 451.]
1650
[166 143 399 261]
0 0 737.354153460417
0 1 686.4397503185148
[451.]
1651
[478 187 568 258]
0 0 700.5905304974838
[451.]
1652
[ 97 204 201 264]
[193 161 398 334]
[ 43 206 131 260]
[387 196 467 257]
0 0 654.9525148264394
1 0 591.6000530844117
2 0 631.8773360639838
3 0 651.016660465153
[451. 452. 453. 454.]
1653
[159 212 257 263]
[242 176 444 312]
0 0 570.7706493678896
0 1 661.5834457373342
0 2 615.2335246207332
0 3 740.2821631030814
1 0 645.9819991109847
1 1 516.007385637834
1 2 616.0004224322228
1 3 646.4016809364672
[451. 452.]
1654
[127 

[311 198 371 247]
0 0 459.46180842383376
0 1 540.9989714089587
0 2 707.8929873290058
[477.]
1727
[]
1728
[339 201 385 232]
[480.]
1729
[ 93 173 228 286]
0 0 929.5928683249563
[480.]
1730
[130 185 232 271]
0 0 850.6793912325259
[480.]
1731
[160 186 259 269]
0 0 891.4238567802446
[480.]
1732
[ 71 181 236 296]
[236 191 336 257]
0 0 980.4080541545995
1 0 951.5181378463286
[480. 481.]
1733
[324 161 400 215]
[158 166 311 251]
0 0 1065.2955422614957
0 1 990.5847724259412
1 0 1129.481400397768
1 1 1105.0833458531304
[481. 480.]
1734
[313 177 436 251]
[447 173 515 227]
[ 98 191 175 233]
[247 168 337 222]
[296 174 400 229]
0 0 1138.8440644471934
0 1 1013.7418232967261
1 0 1095.4170944243622
1 1 1177.0426505831442
2 0 1236.713405947802
2 1 1226.947007334428
3 0 1200.7246159237786
3 1 1212.6478465545135
4 0 1439.3205965446623
4 1 1448.9239108377953
[480. 481. 482. 483. 484.]
1735
[473 197 578 256]
[ 57 197 172 255]
[ 44 217 101 248]
0 0 1048.6215327433172
0 1 993.558854890841
0 2 1103.271240015057

[226 171 428 310]
[145 167 249 253]
0 0 468.9977096720979
0 1 668.8712426662048
1 0 607.0173173237818
1 1 601.0007970509233
[504. 505.]
1828
[184 163 453 353]
0 0 612.9774370241955
0 1 501.6465229917003
[505.]
1829
[ 59 180 192 291]
0 0 578.2392478643924
[505.]
1830
[]
1831
[]
1832
[]
1833
[]
1834
[]
1835
[]
1836
[]
1837
[]
1838
[]
1839
[]
1840
[]
1841
[]
1842
[]
1843
[]
1844
[]
1845
[]
1846
[]
1847
[]
1848
[]
1849
[]
1850
[]
1851
[]
1852
[]
1853
[]
1854
[]
1855
[]
1856
[]
1857
[]
1858
[]
1859
[]
1860
[]
1861
[]
1862
[]
1863
[]
1864
[]
1865
[]
1866
[]
1867
[]
1868
[]
1869
[ 98 165 312 343]
[507.]
1870
[]
1871
[]
1872
[]
1873
[]
1874
[]
1875
[]
1876
[]
1877
[]
1878
[]
1879
[]
1880
[]
1881
[]
1882
[]
1883
[]
1884
[]
1885
[]
1886
[]
1887
[]
1888
[]
1889
[]
1890
[]
1891
[]
1892
[]
1893
[]
1894
[]
1895
[]
1896
[]
1897
[]
1898
[]
1899
[]
1900
[]
1901
[]
1902
[]
1903
[]
1904
[]
1905
[]
1906
[]
1907
[]
1908
[]
1909
[]
1910
[]
1911
[]
1912
[]
1913
[]
1914
[]
1915
[]
1916
[]
1917
[]
1918
[]
1919

[]
1989
[]
1990
[]
1991
[]
1992
[]
1993
[]
1994
[]
1995
[]
1996
[]
1997
[]
1998
[]
1999
[]
2000
[]
2001
[]
2002
[]
2003
[]
2004
[]
2005
[]
2006
[]
2007
[]
2008
[]
2009
[]
2010
[]
2011
[]
2012
[]
2013
[]
2014
[]
2015
[]
2016
[]
2017
[]
2018
[]
2019
[]
2020
[]
2021
[]
2022
[]
2023
[]
2024
[]
2025
[]
2026
[]
2027
[]
2028
[]
2029
[]
2030
[]
2031
[]
2032
[]
2033
[]
2034
[]
2035
[]
2036
[]
2037
[]
2038
[]
2039
[]
2040
[]
2041
[]
2042
[]
2043
[]
2044
[]
2045
[]
2046
[]
2047
[]
2048
[]
2049
[]
2050
[]
2051
[]
2052
[]
2053
[]
2054
[]
2055
[]
2056
[]
2057
[]
2058
[]
2059
[]
2060
[]
2061
[]
2062
[]
2063
[]
2064
[]
2065
[]
2066
[]
2067
[]
2068
[]
2069
[]
2070
[]
2071
[]
2072
[]
2073
[]
2074
[]
2075
[]
2076
[]
2077
[]
2078
[]
2079
[]
2080
[]
2081
[]
2082
[]
2083
[]
2084
[]
2085
[]
2086
[143 155 457 356]
[520.]
2087
[165 160 464 359]
0 0 433.2975742172841
[520.]
2088
[193 166 462 344]
0 0 511.18048121497077
[520.]
2089
[233 174 458 341]
[101 194 227 284]
0 0 544.7637890531909
1 0 722.4963739512107
[

[]
2123
[411 185 458 220]
[534.]
2124
[439 185 498 222]
0 0 611.7433623457459
[534.]
2125
[473 200 532 237]
0 0 518.46025293187
[534.]
2126
[493 195 549 230]
0 0 558.0504018947274
[534.]
2127
[494 200 539 230]
0 0 427.937894954682
[534.]
2128
[]
2129
[]
2130
[408 204 463 235]
[535.]
2131
[]
2132
[ 80 180 169 230]
[536.]
2133
[233 195 280 226]
0 0 523.5656249962877
[536.]
2134
[]
2135
[ 92 200 141 232]
[537.]
2136
[]
2137
[]
2138
[]
2139
[]
2140
[]
2141
[]
2142
[]
2143
[]
2144
[]
2145
[]
2146
[]
2147
[]
2148
[]
2149
[]
2150
[]
2151
[]
2152
[]
2153
[]
2154
[]
2155
[]
2156
[]
2157
[]
2158
[]
2159
[]
2160
[]
2161
[]
2162
[]
2163
[]
2164
[]
2165
[]
2166
[]
2167
[]
2168
[]
2169
[]
2170
[]
2171
[]
2172
[]
2173
[]
2174
[]
2175
[]
2176
[]
2177
[]
2178
[]
2179
[]
2180
[]
2181
[]
2182
[]
2183
[]
2184
[]
2185
[]
2186
[]
2187
[]
2188
[]
2189
[]
2190
[295 197 371 249]
[538.]
2191
[289 195 383 269]
0 0 715.686058143898
[538.]
2192
[277 189 394 293]
0 0 610.9041714351102
[538.]
2193
[240 180 417 316]
